#############################################################################
# Makefile for building: Exercise_project
# Generated by qmake (3.1) (Qt 5.12.2)
# Project:  Exercise_project.pro
# Template: subdirs
# Command: D:\qt\5.12.2\mingw73_64\bin\qmake.exe -o Makefile Exercise_project.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\qt\5.12.2\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\qt\5.12.2\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\qt\5.12.2\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-Course-CourseLib \
		sub-UnitTests \
		sub-Game


sub-Course-CourseLib-qmake_all:  FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Course\CourseLib\ && $(MAKE) -f Makefile qmake_all
sub-Course-CourseLib: FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Course-CourseLib-make_first: FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Course-CourseLib-all: FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Course-CourseLib-clean: FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Course-CourseLib-distclean: FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Course-CourseLib-install_subtargets: FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Course-CourseLib-uninstall_subtargets: FORCE
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-UnitTests-qmake_all: sub-Course-CourseLib-qmake_all FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd UnitTests\ && $(MAKE) -f Makefile qmake_all
sub-UnitTests: sub-Course-CourseLib FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-UnitTests-make_first: sub-Course-CourseLib-make_first FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-UnitTests-all: sub-Course-CourseLib-all FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-UnitTests-clean: sub-Course-CourseLib-clean FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-UnitTests-distclean: sub-Course-CourseLib-distclean FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-UnitTests-install_subtargets: sub-Course-CourseLib-install_subtargets FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-UnitTests-uninstall_subtargets: sub-Course-CourseLib-uninstall_subtargets FORCE
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Game-qmake_all: sub-Course-CourseLib-qmake_all FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Game\ && $(MAKE) -f Makefile qmake_all
sub-Game: sub-Course-CourseLib FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Game-make_first: sub-Course-CourseLib-make_first FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Game-all: sub-Course-CourseLib-all FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Game-clean: sub-Course-CourseLib-clean FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Game-distclean: sub-Course-CourseLib-distclean FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Game-install_subtargets: sub-Course-CourseLib-install_subtargets FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Game-uninstall_subtargets: sub-Course-CourseLib-uninstall_subtargets FORCE
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Exercise_project.pro D:/qt/5.12.2/mingw73_64/mkspecs/win32-g++/qmake.conf D:/qt/5.12.2/mingw73_64/mkspecs/features/spec_pre.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/qdevice.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/device_config.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/common/sanitize.conf \
		D:/qt/5.12.2/mingw73_64/mkspecs/common/gcc-base.conf \
		D:/qt/5.12.2/mingw73_64/mkspecs/common/g++-base.conf \
		D:/qt/5.12.2/mingw73_64/mkspecs/common/angle.conf \
		D:/qt/5.12.2/mingw73_64/mkspecs/common/windows-vulkan.conf \
		D:/qt/5.12.2/mingw73_64/mkspecs/common/g++-win32.conf \
		D:/qt/5.12.2/mingw73_64/mkspecs/qconfig.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/qt_functions.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/qt_config.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/win32-g++/qmake.conf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/exclusive_builds.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/toolchain.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/default_pre.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/win32/default_pre.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/resolve_config.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/default_post.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/qml_debug.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/precompile_header.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/warn_on.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/qmake_use.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/file_copies.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/win32/windows.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/testcase_targets.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/exceptions.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/yacc.prf \
		D:/qt/5.12.2/mingw73_64/mkspecs/features/lex.prf \
		Exercise_project.pro
	$(QMAKE) -o Makefile Exercise_project.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
D:/qt/5.12.2/mingw73_64/mkspecs/features/spec_pre.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/qdevice.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/features/device_config.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/common/sanitize.conf:
D:/qt/5.12.2/mingw73_64/mkspecs/common/gcc-base.conf:
D:/qt/5.12.2/mingw73_64/mkspecs/common/g++-base.conf:
D:/qt/5.12.2/mingw73_64/mkspecs/common/angle.conf:
D:/qt/5.12.2/mingw73_64/mkspecs/common/windows-vulkan.conf:
D:/qt/5.12.2/mingw73_64/mkspecs/common/g++-win32.conf:
D:/qt/5.12.2/mingw73_64/mkspecs/qconfig.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_core.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_help.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_location.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_network.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
D:/qt/5.12.2/mingw73_64/mkspecs/features/qt_functions.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/qt_config.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/win32-g++/qmake.conf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
D:/qt/5.12.2/mingw73_64/mkspecs/features/exclusive_builds.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/toolchain.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/default_pre.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/win32/default_pre.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/resolve_config.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/default_post.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/qml_debug.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/precompile_header.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/warn_on.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/qmake_use.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/file_copies.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/win32/windows.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/testcase_targets.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/exceptions.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/yacc.prf:
D:/qt/5.12.2/mingw73_64/mkspecs/features/lex.prf:
Exercise_project.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Exercise_project.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-Course-CourseLib-qmake_all sub-UnitTests-qmake_all sub-Game-qmake_all FORCE

make_first: sub-Course-CourseLib-make_first sub-UnitTests-make_first sub-Game-make_first  FORCE
all: sub-Course-CourseLib-all sub-UnitTests-all sub-Game-all  FORCE
clean: sub-Course-CourseLib-clean sub-UnitTests-clean sub-Game-clean  FORCE
distclean: sub-Course-CourseLib-distclean sub-UnitTests-distclean sub-Game-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Course-CourseLib-install_subtargets sub-UnitTests-install_subtargets sub-Game-install_subtargets FORCE
uninstall_subtargets: sub-Course-CourseLib-uninstall_subtargets sub-UnitTests-uninstall_subtargets sub-Game-uninstall_subtargets FORCE

sub-Course-CourseLib-debug:
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-UnitTests-debug: sub-Course-CourseLib-debug
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Game-debug: sub-Course-CourseLib-debug
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-Course-CourseLib-debug sub-UnitTests-debug sub-Game-debug

sub-Course-CourseLib-release:
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-UnitTests-release: sub-Course-CourseLib-release
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Game-release: sub-Course-CourseLib-release
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-Course-CourseLib-release sub-UnitTests-release sub-Game-release

sub-Course-CourseLib-check:
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-UnitTests-check: sub-Course-CourseLib-check
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Game-check: sub-Course-CourseLib-check
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-Course-CourseLib-check sub-UnitTests-check sub-Game-check

sub-Course-CourseLib-benchmark:
	@if not exist Course\CourseLib\ mkdir Course\CourseLib\ & if not exist Course\CourseLib\ exit 1
	cd Course\CourseLib\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Course\CourseLib\CourseLib.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-UnitTests-benchmark: sub-Course-CourseLib-benchmark
	@if not exist UnitTests\ mkdir UnitTests\ & if not exist UnitTests\ exit 1
	cd UnitTests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\UnitTests\UnitTests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Game-benchmark: sub-Course-CourseLib-benchmark
	@if not exist Game\ mkdir Game\ & if not exist Game\ exit 1
	cd Game\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Nikke\Desktop\project\oijoi\Game\Game.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Course-CourseLib-benchmark sub-UnitTests-benchmark sub-Game-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

